
const fs = require('fs');
const util = require('util');
const readFileAsync = util.promisify(fs.readFile);

module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    let message;
    try {
        message = await readFileAsync('./GetMessage/content.txt');
    } catch (err) {
        context.log.error('ERROR', err);
        // This rethrown exception will be handled by the Functions Runtime and will only fail the individual invocation
        throw err;
    }

    context.res = {
        // status: 200, /* Defaults to 200 */
        body: message
    };
}